;; Auto generated by `pyim-generate-dict-cache-file', don't edit it by hand!

#s(hash-table size 1000000 test equal rehash-size 1.5 rehash-threshold 0.8 data ("你好" (:count 2) "中华" (:count 2) "哈哈" (:count 3) "你是" (:count 2) "共和国" (:count 2) "我爱你" (:count 2)))
